/* Generated By:JavaCC: Do not edit this line. Simple3Constants.java */
package util.text.parse;

public interface Simple3Constants {

  int EOF = 0;
  int LBRACE = 5;
  int RBRACE = 6;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"{\"",
    "\"}\"",
  };

}
